// <auto-generated />
using Lab18Cameorn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab18Cameorn.Migrations
{
    [DbContext(typeof(Lab18CameornContext))]
    [Migration("20171016164632_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab18Cameorn.Models.Destinations", b =>
                {
                    b.Property<int>("DestinationsID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Climate");

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.HasKey("DestinationsID");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Lab18Cameorn.Models.Supplies", b =>
                {
                    b.Property<int>("SuppliesID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Qty");

                    b.HasKey("SuppliesID");

                    b.ToTable("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
