// <auto-generated />
using lab18miya.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace lab18miya.Migrations
{
    [DbContext(typeof(lab18miyaContext))]
    [Migration("20171005183123_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab18miya.Models.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("WeatherID");

                    b.HasKey("DestinationID");

                    b.HasIndex("WeatherID");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("lab18miya.Models.Supplies", b =>
                {
                    b.Property<int>("SupplyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<int>("WeatherID");

                    b.HasKey("SupplyID");

                    b.HasIndex("WeatherID");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("lab18miya.Models.Weather", b =>
                {
                    b.Property<int>("WeatherID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("WeatherType");

                    b.HasKey("WeatherID");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("lab18miya.Models.Destination", b =>
                {
                    b.HasOne("lab18miya.Models.Weather", "Weather")
                        .WithMany("Destination")
                        .HasForeignKey("WeatherID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("lab18miya.Models.Supplies", b =>
                {
                    b.HasOne("lab18miya.Models.Weather", "Weather")
                        .WithMany("Supplies")
                        .HasForeignKey("WeatherID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
