// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TravelPacker.Models;

namespace TravelPacker.Migrations
{
    [DbContext(typeof(TravelPackerContext))]
    [Migration("20171007071433_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelPacker.Models.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Climate");

                    b.Property<string>("LocationName");

                    b.HasKey("DestinationID");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("TravelPacker.Models.DestinationProducts", b =>
                {
                    b.Property<int>("DestinationProductsID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DestinationID");

                    b.Property<int>("ProductID");

                    b.HasKey("DestinationProductsID");

                    b.HasIndex("DestinationID");

                    b.HasIndex("ProductID");

                    b.ToTable("DestinationProducts");
                });

            modelBuilder.Entity("TravelPacker.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("ProductID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TravelPacker.Models.DestinationProducts", b =>
                {
                    b.HasOne("TravelPacker.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelPacker.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
